In [40]:
import numpy as np

In [41]:
def Cal_LU(D,g):
    A=np.array((D),dtype=float)
    f=np.array((g),dtype=float)
    n = f.size
    for i in range(0,n-1):     # Loop through the columns of the matrix
        for j in range(i+1,n):     # Loop through rows below diagonal for each column
            if A[i,i] == 0:
                print("Error: Zero on diagonal!")
                print("Need algorithm with pivoting")
                break
            m = A[j,i]/A[i,i]
            A[j,:] = A[j,:] - m*A[i,:]
            f[j] = f[j] - m*f[i]
    return A,f

In [42]:
def Back_Subs(A,f):
    n = f.size
    x = np.zeros(n)             # Initialize the solution vector, x, to zero
    x[n-1] = f[n-1]/A[n-1,n-1]    # Solve for last entry first
    for i in range(n-2,-1,-1):      # Loop from the end to the beginning
        sum_ = 0
        for j in range(i+1,n):        # For known x values, sum and move to rhs
            sum_ = sum_ + A[i,j]*x[j]
        x[i] = (f[i] - sum_)/A[i,i]
    return x

In [43]:
A = np.array([[2,3,5],[3,4,1],[6,7,2]])
f = np.array([23,14,26])
B,g = Cal_LU(A,f)
x= Back_Subs(B,g)
print(x)

[1. 2. 3.]


In [44]:
y = np.linalg.solve(A,f)
print(y)

[1. 2. 3.]


In [45]:
A = np.array([[0.9,0.3,0.1], [0.1,0.5,0.2],[0,0.2,0.7]])
f = np.array([30.0,25.0,10.0])
B,g = Cal_LU(A,f)
x = Back_Subs(B,g)
print(x)

[17.88461538 45.96153846  1.15384615]


In [46]:
x = np.linalg.solve(A,f)
print(x)

[17.88461538 45.96153846  1.15384615]


In [47]:
def Cal_LU_pivot(D,g):
    A=np.array((D),dtype=float)
    f=np.array((g),dtype=float)
    n = len(f)
    for i in range(0,n-1):     # Loop through the columns of the matrix
        
        if np.abs(A[i,i])==0:
            for k in range(i+1,n):
                if np.abs(A[k,i])>np.abs(A[i,i]):
                    A[[i,k]]=A[[k,i]]             # Swaps ith and kth rows to each other
                    f[[i,k]]=f[[k,i]]
                    break
                    
        for j in range(i+1,n):     # Loop through rows below diagonal for each column
            m = A[j,i]/A[i,i]
            A[j,:] = A[j,:] - m*A[i,:]
            f[j] = f[j] - m*f[i]
    return A,f

In [48]:
A = np.array([[0,3,5],[3,0,1],[6,7,2]])
f = np.array([23,14,26])
B,g = Cal_LU_pivot(A,f)
x= Back_Subs(B,g)
print(x)

[ 3.07619048 -0.28571429  4.77142857]


In [49]:
x = np.linalg.solve(A,f)
print(x)

[ 3.07619048 -0.28571429  4.77142857]


In [50]:
def Cal_JE_Partial_Piovting(D,g):
    A=np.array((D),dtype=float)
    f=np.array((g),dtype=float)
    n = len(f)

    for i in range(0,n-1):        # Loop through the columns of the matrix 
        
        for k in range(i+1,n):    # loop for find max element under pivot element
            if np.abs(A[i,i]) < np.abs(A[k,i]):
                A[[i,k]]=A[[k,i]]             # Swaps ith and kth rows to each other
                f[[i,k]]=f[[k,i]]
                
                print('======================================')
                print('swich row no :',i+1,'with row no',k+1,':\n',A)
        
        for j in range(i+1,n):     # Loop through rows below diagonal for each column
            m = A[j,i]/A[i,i]
            A[j,:] = A[j,:] - m*A[i,:]
            f[j] = f[j] - m*f[i]
     
        print('======================================')
        print('solve piovtal element no :',i+1,'\n',A)
                
    return A,f

In [51]:
A = np.array([[1,0,2,3],[-1,2,2,-3],[0,1,1,4],[6,2,2,4]])
print(A) 
f = np.array([1,-1,2,1])
B,g = Cal_JE_Partial_Piovting(A,f)
x= Back_Subs(B,g)
print('======================================')
print('the group of solution is:\n',x)
#print(np.max(A[0,:]))

[[ 1  0  2  3]
 [-1  2  2 -3]
 [ 0  1  1  4]
 [ 6  2  2  4]]
swich row no : 1 with row no 4 :
 [[ 6.  2.  2.  4.]
 [-1.  2.  2. -3.]
 [ 0.  1.  1.  4.]
 [ 1.  0.  2.  3.]]
solve piovtal element no : 1 
 [[ 6.          2.          2.          4.        ]
 [ 0.          2.33333333  2.33333333 -2.33333333]
 [ 0.          1.          1.          4.        ]
 [ 0.         -0.33333333  1.66666667  2.33333333]]
solve piovtal element no : 2 
 [[ 6.          2.          2.          4.        ]
 [ 0.          2.33333333  2.33333333 -2.33333333]
 [ 0.          0.          0.          5.        ]
 [ 0.          0.          2.          2.        ]]
swich row no : 3 with row no 4 :
 [[ 6.          2.          2.          4.        ]
 [ 0.          2.33333333  2.33333333 -2.33333333]
 [ 0.          0.          2.          2.        ]
 [ 0.          0.          0.          5.        ]]
solve piovtal element no : 3 
 [[ 6.          2.          2.          4.        ]
 [ 0.          2.33333333  2.333333

In [52]:
x = np.linalg.solve(A,f)
print(x)

[-0.18571429  0.22857143 -0.11428571  0.47142857]
