In [1]:
import numpy as np

In [2]:
# system matrix
#A = np.array([[1,1,-1],[1,2,-2],[-2,1,1]])
A = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
b = np.array([1,1,1])

## forward substitution

In [3]:
def for_sub(L, b):
    
    n = L.shape[0]
    y = np.zeros_like(b, dtype=np.double)
    y[0] = b[0] / L[0, 0]
    
    for i in range(n):
     
        s = sum(L[i,j] * y[j] for j in range(i))
        y[i] = (b[i] - s )/ L[i,i]
        
    return y

## backward substitution

In [4]:
def bac_sub(U, y):
    
    n = U.shape[0]
    x = np.zeros_like(y, dtype=np.double)
    x[n-1] = y[n-1] / U[n-1,n-1]
    
    for i in range(n-1,-1,-1):
         
        s = sum(U[i,j] * x[j] for j in range(i+1,n))
        x[i] = (y[i] - s) / U[i,i]
        
    return x

## Doolittle decomposition

In [5]:
def doolittle(A):
    
    n = A.shape[0]
    
    U = np.zeros((n, n), dtype=np.double)
    L = np.eye(n, dtype=np.double)
    
    for i in range(n):
        
        for j in range(i,n):
            
            s1 = sum(L[i][k] * U[k][j] for k in range(i))
            U[i,j]= A[i,j]- s1
            s1 = 0
            
        for j in range(i+1,n):
            s2 = sum(L[j][k] * U[k][i] for k in range(i))
            L[j][i] = (A[j][i] - s2) / U[i][i]
            s2 = 0
            
    return L, U

In [6]:
l,u = doolittle(A)
print('d-lower matrix\n',l,'\n','d-uper matrix\n',u,'\n')

y = for_sub(l,b)
print('y matrix=\n',y)
x = bac_sub(u,y)
print('the group of solution is: \n',x)

d-lower matrix
 [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.         -0.66666667  1.        ]] 
 d-uper matrix
 [[ 2.         -1.          0.        ]
 [ 0.          1.5        -1.        ]
 [ 0.          0.          1.33333333]] 

y matrix=
 [1.  1.5 2. ]
the group of solution is: 
 [1.5 2.  1.5]


## crout decomposition

In [7]:
def crout(a):
    
    n = a.shape[0]
    
    U = np.zeros((n, n), dtype=np.double)
    L = np.zeros((n, n), dtype=np.double)
    s1 = 0
    s2 = 0

    for i in range(n):
        
        L[i][0] = a[i][0]
        U[i][i] = 1
        
        for j in range(1, n):
            
            U[0][j] = A[0][j] / L[0][0]
            
        for k in range(1, n):
            
            for i in range(k, n):
                
                s1 = sum(L[i][r] * U[r][k] for r in range(k))
                L[i][k] = A[i][k] - s1
                s1 = 0  
                
            for j in range(k+1, n):
                
                s2 = sum(L[k][r] * U[r][j] for r in range(k))
                U[k][j] = (A[k][j] - s2) / L[k][k]
                s2 = 0 
                
    return L, U

In [8]:
l,u = crout(A)
print('c-lower matrix\n',l,'\n','c-uper matrix\n',u,'\n')

y = for_sub(l,b)
print('y matrix=\n',y)
x = bac_sub(u,y)
print('the group of solution is: \n',x)

c-lower matrix
 [[ 2.          0.          0.        ]
 [-1.          1.5         0.        ]
 [ 0.         -1.          1.33333333]] 
 c-uper matrix
 [[ 1.         -0.5         0.        ]
 [ 0.          1.         -0.66666667]
 [ 0.          0.          1.        ]] 

y matrix=
 [0.5 1.  1.5]
the group of solution is: 
 [1.5 2.  1.5]


## cholesky decomposition

In [9]:
def cholesky(A):
    
    n = A.shape[0]
    U = np.zeros((n, n), dtype=np.double)
    
    for i in range(n):
        
        s0 = sum(U[k][i] * U[k][i] for k in range(i))
        U[i, i] = np.sqrt(A[i,i] - s0 )
        s0 = 0
               
        for j in range(i+1,n):
                   
            s1 = sum(U[k,i] * U[k,j] for k in range(i))
            U[i,j] = (A[i,j] - s1) / U[i, i]
            s1 = 0
    L=U.T
    return L,U

In [10]:
l,u = cholesky(A)
print('ch-lower matrix\n',l,'\n','ch-uper matrix\n',u,'\n')

y = for_sub(l,b)
print('y matrix=\n',y)
x = bac_sub(u,y)
print('the group of solution is: \n',x)

ch-lower matrix
 [[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]] 
 ch-uper matrix
 [[ 1.41421356 -0.70710678  0.        ]
 [ 0.          1.22474487 -0.81649658]
 [ 0.          0.          1.15470054]] 

y matrix=
 [0.70710678 1.22474487 1.73205081]
the group of solution is: 
 [1.5 2.  1.5]


In [11]:
cholesky_factor = np.linalg.cholesky(A)

print(cholesky_factor)

[[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]


In [14]:
a = [[1,3,2],[2,2,4],[1,5,6]]
print(np.linalg.inv(a))

[[ 0.5    0.5   -0.5  ]
 [ 0.5   -0.25   0.   ]
 [-0.5    0.125  0.25 ]]
