In [885]:
import numpy as np

In [886]:
# system matrix
#A = np.array([[1,1,-1],[1,2,-2],[-2,1,1]])
A = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
b = np.array([1,1,1])

## forward substitution

In [887]:
def for_sub(L, b):
    
    n = L.shape[0]
    y = np.zeros_like(b, dtype=np.double)
    y[0] = b[0] / L[0, 0]
    
    for i in range(1, n):
        y[i] = (b[i] - np.dot(L[i,:i], y[:i])) / L[i,i]
        
    return y

## backward substitution

In [888]:
def bac_sub(U, y):
    
    n = U.shape[0]
    x = np.zeros_like(y, dtype=np.double)
    x[-1] = y[-1] / U[-1, -1]
    
    for i in range(n-2, -1, -1):
        x[i] = (y[i] - np.dot(U[i,i:], x[i:])) / U[i,i]
        
    return x

## Doolittle decomposition

In [889]:
def doolittle(A):
    
    n = A.shape[0]
    
    U = np.zeros((n, n), dtype=np.double)
    L = np.eye(n, dtype=np.double)
    
    for k in range(n):
        
        U[k, k:] = A[k, k:] - L[k,:k] @ U[:k,k:]
        L[(k+1):,k] = (A[(k+1):,k] - L[(k+1):,:] @ U[:,k]) / U[k, k]
    
    return L, U

In [890]:
l,u = doolittle(A)
print('d-lower matrix\n',l,'\n','d-uper matrix\n',u,'\n')

y = for_sub(l,b)
x = bac_sub(u,y)
print('the group of solution is: \n',x)

d-lower matrix
 [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.         -0.66666667  1.        ]] 
 d-uper matrix
 [[ 2.         -1.          0.        ]
 [ 0.          1.5        -1.        ]
 [ 0.          0.          1.33333333]] 

the group of solution is: 
 [1.5 2.  1.5]


## crout decomposition

In [891]:
def crout(A):
    
    n = A.shape[0]
    
    U = np.zeros((n, n), dtype=np.double)
    L = np.zeros((n, n), dtype=np.double)
    
    for k in range(n):
        
        L[k, k] = A[k, k] - L[k, :] @ U[:, k]
        
        U[k, k:] = (A[k, k:] - L[k, :k] @ U[:k, k:]) / L[k, k]
        L[(k+1):, k] = (A[(k+1):, k] - L[(k+1):, :] @ U[:, k]) / U[k, k]
    
    return L, U

In [892]:
l,u = crout(A)
print('c-lower matrix\n',l,'\n','c-uper matrix\n',u,'\n')

y = for_sub(l,b)
x = bac_sub(u,y)
print('the group of solution is: \n',x)

c-lower matrix
 [[ 2.          0.          0.        ]
 [-1.          1.5         0.        ]
 [ 0.         -1.          1.33333333]] 
 c-uper matrix
 [[ 1.         -0.5         0.        ]
 [ 0.          1.         -0.66666667]
 [ 0.          0.          1.        ]] 

the group of solution is: 
 [1.5 2.  1.5]


## cholesky decomposition

In [893]:
def cholesky(A):
    
    n = A.shape[0]
    U = np.zeros((n, n), dtype=np.double)
    
    for k in range(n):
        U[k, k] = np.sqrt(A[k,k] - np.sum(U[:,k] ** 2))
        U[k,(k+1):] = (A[k,(k+1):] - np.sum(np.dot(U[:,k] , U[:,(k+1):]))) / U[k, k]
    L=U.T
    return L,U

In [894]:
l,u = cholesky(A)
print('ch-lower matrix\n',l,'\n','ch-uper matrix\n',u,'\n')

y = for_sub(l,b)
x = bac_sub(u,y)
print('the group of solution is: \n',x)

ch-lower matrix
 [[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]] 
 ch-uper matrix
 [[ 1.41421356 -0.70710678  0.        ]
 [ 0.          1.22474487 -0.81649658]
 [ 0.          0.          1.15470054]] 

the group of solution is: 
 [1.5 2.  1.5]


In [895]:
print(A)
k=2
print(A[:k,k])
print(A[k:,k])

[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
[ 0 -1]
[2]
